Disable Apparmor unit test
DebCI latest error is apparently missing securityfs in the Debian
kernel used for DebCI despite Apparmor being enabled by default
now in Debian.

As a result Apparmor test produces:
test_zz_apparmor (__main__.BasicTest)
Test apparmor ... FAIL

======================================================================
FAIL: test_zz_apparmor (__main__.BasicTest)
Test apparmor
----------------------------------------------------------------------
Traceback (most recent call last):
  File /tmp/autopkgtest-lxc.06l0vu6_/downtmp/build.ruz/src/debian/tests/test-squid.py, line 206, in test_zz_apparmor
    self.assertEquals(ret, expected, result + report)
AssertionError: Got exit code 1, expected 0
Setting /etc/apparmor.d/usr.sbin.squid to enforce mode.

ERROR: Warning: unable to find a suitable fs in /proc/mounts, is it mounted?
Use --subdomainfs to override.